### ISSUE TITLE
Question: what's the version compatibility between databend-query and databend-jdbc?

### ISSUE THREAD

**Issue by Px951213** [databendcloud/databend-jdbc#67]
When I use databend-jdbc:**0.0.8** execute a replace statement in databend-query:**v1.1.46** , the following exception happend:
```
java.sql.SQLException: Error executing query: Error fetching next (attempts: 36, duration: PT1M3.379821179S)cause: java.io.UncheckedIOException: java.net.ProtocolException: Unexpected status line: �
	at com.databend.jdbc.DatabendStatement.internalExecute(DatabendStatement.java:225)
	at com.databend.jdbc.DatabendStatement.execute(DatabendStatement.java:172)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:632)
         ......
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Error fetching next (attempts: 36, duration: PT1M3.379821179S)
	at com.databend.client.DatabendClientV1.executeInternal(DatabendClientV1.java:134)
	at com.databend.client.DatabendClientV1.execute(DatabendClientV1.java:187)
	at com.databend.client.DatabendClientV1.<init>(DatabendClientV1.java:81)
	at com.databend.jdbc.DatabendConnection.startQuery(DatabendConnection.java:514)
	at com.databend.jdbc.DatabendStatement.internalExecute(DatabendStatement.java:208)
	... 13 more
Caused by: java.io.UncheckedIOException: java.net.ProtocolException: Unexpected status line: �
	at com.databend.client.JsonResponse.execute(JsonResponse.java:115)
	at com.databend.client.DatabendClientV1.executeInternal(DatabendClientV1.java:153)
	... 17 more
Caused by: java.net.ProtocolException: Unexpected status line: �
	at okhttp3.internal.http.StatusLine$Companion.parse(StatusLine.kt:77)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:179)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:111)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.databend.client.OkHttpUtils.lambda$basicAuthInterceptor$1(OkHttpUtils.java:46)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.databend.client.OkHttpUtils.lambda$userAgentInterceptor$0(OkHttpUtils.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
	at com.databend.client.JsonResponse.execute(JsonResponse.java:73)
	... 18 more
```

Is there a version compatibility question or did i miss something ?

**Comment by hantmac** [comment]
Hi @Px951213  Databend jdbc is developed for >= databend v1.0.0 so this problem is not caused by version compatibility. From the error log, it may be a network problem, timeout for example.

**Comment by Px951213** [comment]
> Hi @Px951213 Databend jdbc is developed for >= databend v1.0.0 so this problem is not caused by version compatibility. From the error log, it may be a network problem, timeout for example.

Thanks, I'll retry this later

**Comment by Px951213** [comment]
I tried 8000 port rather than 3307 and it worked !
